import type {
  AegisFile,
  ApiKey,
  AuditEvent,
  Policy,
  StorageBackend,
  TeamMember,
} from "./types";

/**
 * Fixed base "now" so SSR and client produce identical strings.
 * Mock-only — replace with real timestamps when wired to backend.
 */
const NOW = new Date("2026-05-23T19:00:00.000Z").getTime();
const ago = (ms: number) => new Date(NOW - ms).toISOString();

/** Deterministic pseudo-random (mulberry32) so SSR and client match. */
function makeRng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ---------- Files ---------- */

export const files: AegisFile[] = [
  {
    id: "f_01HX",
    originalName: "Q3-investor-deck-FINAL_v7.pdf",
    renamedTo: "AMZN_AMAZON_INVESTORDAY_2024Q3_EN_2024-09-12.pdf",
    size: 4_812_440,
    mimeType: "application/pdf",
    ticker: "AMZN",
    publisher: "AMAZON",
    reportType: "INVESTORDAY",
    yearQuarter: "2024Q3",
    publicationDate: "2024-09-12",
    sensitivity: "confidential",
    sensitivityScore: 78,
    status: "encrypted",
    encryption: "aes256",
    framework: ["SOC2", "ISO27001"],
    entities: [
      { type: "EIN", count: 3 },
      { type: "EMAIL", count: 18 },
    ],
    uploadedBy: "Maya Patel",
    uploadedAt: ago(1000 * 60 * 23),
    storage: "vault",
    hash: "sha256:6f4a91e2c7db…3e2f",
    tags: ["earnings", "internal-only"],
  },
  {
    id: "f_02HX",
    originalName: "patient_records_export.csv",
    renamedTo: "ACME_CLINIC_PHI_EXPORT_2025Q1_EN_2025-02-14.csv",
    size: 1_204_991,
    mimeType: "text/csv",
    sensitivity: "restricted",
    sensitivityScore: 96,
    status: "encrypted",
    encryption: "client-managed",
    framework: ["HIPAA", "SOC2"],
    entities: [
      { type: "SSN", count: 412 },
      { type: "MRN", count: 412 },
      { type: "PHI", count: 1031 },
    ],
    uploadedBy: "Dr. Helen Cho",
    uploadedAt: ago(1000 * 60 * 60 * 2),
    storage: "vault",
    hash: "sha256:9a02ccef1bb1…7011",
    tags: ["phi", "audit-required"],
  },
  {
    id: "f_03HX",
    originalName: "vendor_msa_morgan_stanley.docx",
    renamedTo: "MS_LEGAL_MSA_2024Q4_EN_2024-11-08.docx",
    size: 287_443,
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    sensitivity: "confidential",
    sensitivityScore: 64,
    status: "renamed",
    encryption: "aes256",
    framework: ["SOC2"],
    entities: [
      { type: "EMAIL", count: 6 },
      { type: "PHONE", count: 2 },
    ],
    uploadedBy: "Jon Reyes",
    uploadedAt: ago(1000 * 60 * 60 * 5),
    storage: "s3",
    hash: "sha256:4b117ac0…aa31",
    tags: ["legal", "vendor"],
  },
  {
    id: "f_04HX",
    originalName: "marketing_brief_2025.pptx",
    renamedTo: "ACME_MARKETING_BRIEF_2025Q1_EN_2025-01-22.pptx",
    size: 8_120_998,
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    sensitivity: "internal",
    sensitivityScore: 22,
    status: "renamed",
    encryption: "none",
    framework: [],
    entities: [],
    uploadedBy: "Priya Shah",
    uploadedAt: ago(1000 * 60 * 60 * 9),
    storage: "s3",
    hash: "sha256:81ae2f…0c12",
    tags: ["marketing"],
  },
  {
    id: "f_05HX",
    originalName: "wire_routing_payments.xlsx",
    renamedTo: "ACME_FINANCE_PAYMENTS_2025Q1_EN_2025-03-04.xlsx",
    size: 612_881,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    sensitivity: "restricted",
    sensitivityScore: 92,
    status: "encrypted",
    encryption: "aes256",
    framework: ["PCI-DSS", "FINRA", "SOC2"],
    entities: [
      { type: "ROUTING", count: 24 },
      { type: "BANK_ACCOUNT", count: 24 },
    ],
    uploadedBy: "Maya Patel",
    uploadedAt: ago(1000 * 60 * 60 * 13),
    storage: "vault",
    hash: "sha256:cc01b8…f4ee",
    tags: ["finance", "regulated"],
  },
  {
    id: "f_06HX",
    originalName: "press_release_draft.txt",
    renamedTo: "ACME_PR_DRAFT_2025Q1_EN_2025-03-19.txt",
    size: 14_120,
    mimeType: "text/plain",
    sensitivity: "public",
    sensitivityScore: 6,
    status: "renamed",
    encryption: "none",
    framework: [],
    entities: [],
    uploadedBy: "Priya Shah",
    uploadedAt: ago(1000 * 60 * 60 * 26),
    storage: "s3",
    hash: "sha256:0ab1…91de",
    tags: ["public"],
  },
  {
    id: "f_07HX",
    originalName: "sec_filing_10K_2024.pdf",
    renamedTo: "AMZN_SEC_10-K_2024Q0_EN_2025-02-01.pdf",
    size: 12_440_991,
    mimeType: "application/pdf",
    ticker: "AMZN",
    publisher: "SEC",
    reportType: "10-K",
    yearQuarter: "2024Q0",
    publicationDate: "2025-02-01",
    sensitivity: "internal",
    sensitivityScore: 18,
    status: "archived",
    encryption: "aes256",
    framework: ["FINRA", "SOC2"],
    entities: [{ type: "EIN", count: 1 }],
    uploadedBy: "Compliance Bot",
    uploadedAt: ago(1000 * 60 * 60 * 49),
    storage: "filecoin",
    hash: "sha256:71ee92…aa70",
    tags: ["sec", "10K", "immutable"],
  },
  {
    id: "f_08HX",
    originalName: "internal_keys.env",
    sensitivity: "restricted",
    sensitivityScore: 99,
    size: 4_122,
    mimeType: "text/plain",
    status: "failed",
    encryption: "none",
    framework: ["SOC2", "ISO27001"],
    entities: [
      { type: "API_KEY", count: 7 },
    ],
    uploadedBy: "Jon Reyes",
    uploadedAt: ago(1000 * 60 * 9),
    storage: "s3",
    hash: "sha256:dead…beef",
    tags: ["secrets", "blocked"],
  },
  {
    id: "f_09HX",
    originalName: "evercore_amzn_initiation.pdf",
    renamedTo: "AMZN_EVERCORE_ANALYSTREPORT_INIT_2024Q4_EN_2024-12-04.pdf",
    size: 3_220_109,
    mimeType: "application/pdf",
    ticker: "AMZN",
    publisher: "EVERCORE",
    reportType: "ANALYSTREPORT",
    yearQuarter: "2024Q4",
    publicationDate: "2024-12-04",
    sensitivity: "internal",
    sensitivityScore: 28,
    status: "renamed",
    encryption: "aes256",
    framework: ["SOC2"],
    entities: [{ type: "EMAIL", count: 4 }],
    uploadedBy: "Maya Patel",
    uploadedAt: ago(1000 * 60 * 60 * 72),
    storage: "arweave",
    hash: "sha256:aa19…ff20",
    tags: ["research", "analyst"],
  },
  {
    id: "f_10HX",
    originalName: "amzn_q2_earnings_call.txt",
    renamedTo: "AMZN_AMAZON_EARNINGS_CALL_2021Q2_EN_2021-07-29.txt",
    size: 86_002,
    mimeType: "text/plain",
    ticker: "AMZN",
    publisher: "AMAZON",
    reportType: "EARNINGS_CALL",
    yearQuarter: "2021Q2",
    publicationDate: "2021-07-29",
    sensitivity: "public",
    sensitivityScore: 4,
    status: "archived",
    encryption: "none",
    framework: [],
    entities: [],
    uploadedBy: "Compliance Bot",
    uploadedAt: ago(1000 * 60 * 60 * 96),
    storage: "filecoin",
    hash: "sha256:11ba…cc01",
    tags: ["earnings", "public"],
  },
];

/* ---------- Audit ---------- */

export const auditEvents: AuditEvent[] = [
  {
    id: "ev_001",
    timestamp: ago(1000 * 60 * 2),
    actor: "Maya Patel",
    action: "file.encrypt",
    resource: "AMZN_AMAZON_INVESTORDAY_2024Q3_EN_2024-09-12.pdf",
    outcome: "success",
    ip: "10.0.4.221",
    hash: "0x4e7a3c8b21f0",
    prevHash: "0x9c11abc02218",
  },
  {
    id: "ev_002",
    timestamp: ago(1000 * 60 * 9),
    actor: "Jon Reyes",
    action: "file.upload",
    resource: "internal_keys.env",
    outcome: "denied",
    ip: "10.0.4.18",
    hash: "0x9c11abc02218",
    prevHash: "0x77eecaa4ac90",
    metadata: { policy: "Block-Plaintext-Secrets", entities: 7 },
  },
  {
    id: "ev_003",
    timestamp: ago(1000 * 60 * 17),
    actor: "Compliance Bot",
    action: "policy.evaluate",
    resource: "patient_records_export.csv",
    outcome: "warning",
    ip: "127.0.0.1",
    hash: "0x77eecaa4ac90",
    prevHash: "0x012ac1981b9c",
    metadata: { framework: "HIPAA", score: 96 },
  },
  {
    id: "ev_004",
    timestamp: ago(1000 * 60 * 24),
    actor: "Dr. Helen Cho",
    action: "key.rotate",
    resource: "kms-key-prod/aegis-vault-2",
    outcome: "success",
    ip: "10.0.4.42",
    hash: "0x012ac1981b9c",
    prevHash: "0x551beac9d710",
  },
  {
    id: "ev_005",
    timestamp: ago(1000 * 60 * 41),
    actor: "Priya Shah",
    action: "auth.mfa.enable",
    resource: "user/priya@acme.io",
    outcome: "success",
    ip: "172.20.10.4",
    hash: "0x551beac9d710",
    prevHash: "0xa0119c3e88e1",
  },
  {
    id: "ev_006",
    timestamp: ago(1000 * 60 * 67),
    actor: "Compliance Bot",
    action: "file.archive",
    resource: "AMZN_SEC_10-K_2024Q0_EN_2025-02-01.pdf",
    outcome: "success",
    ip: "127.0.0.1",
    hash: "0xa0119c3e88e1",
    prevHash: "0xb2c08fa01a32",
    metadata: { backend: "filecoin", immutable: 1 },
  },
  {
    id: "ev_007",
    timestamp: ago(1000 * 60 * 90),
    actor: "Maya Patel",
    action: "policy.create",
    resource: "policy/SSN-Auto-Encrypt",
    outcome: "success",
    ip: "10.0.4.221",
    hash: "0xb2c08fa01a32",
    prevHash: "0xfe771b201aa9",
  },
  {
    id: "ev_008",
    timestamp: ago(1000 * 60 * 60 * 2),
    actor: "Jon Reyes",
    action: "api_key.revoke",
    resource: "key/sk-prod-•••aa12",
    outcome: "success",
    ip: "10.0.4.18",
    hash: "0xfe771b201aa9",
    prevHash: "0x33aa01b2e10c",
  },
  {
    id: "ev_009",
    timestamp: ago(1000 * 60 * 60 * 5),
    actor: "system",
    action: "scan.scheduled",
    resource: "vault/all",
    outcome: "success",
    ip: "127.0.0.1",
    hash: "0x33aa01b2e10c",
    prevHash: "0x019ae28b9001",
    metadata: { scanned: 4218, flagged: 17 },
  },
  {
    id: "ev_010",
    timestamp: ago(1000 * 60 * 60 * 9),
    actor: "Helen Cho",
    action: "share.link.create",
    resource: "AMZN_EVERCORE_ANALYSTREPORT_INIT_2024Q4_EN_2024-12-04.pdf",
    outcome: "success",
    ip: "10.0.4.42",
    hash: "0x019ae28b9001",
    prevHash: "0x441c19acdd01",
    metadata: { expires_in: "24h", watermarked: 1 },
  },
];

/* ---------- Team ---------- */

export const team: TeamMember[] = [
  {
    id: "u_01",
    name: "Maya Patel",
    email: "maya@acme.io",
    role: "Owner",
    status: "active",
    lastActive: ago(1000 * 60 * 4),
    mfa: true,
    department: "Security",
    initials: "MP",
  },
  {
    id: "u_02",
    name: "Jon Reyes",
    email: "jon@acme.io",
    role: "Admin",
    status: "active",
    lastActive: ago(1000 * 60 * 32),
    mfa: true,
    department: "Engineering",
    initials: "JR",
  },
  {
    id: "u_03",
    name: "Helen Cho",
    email: "helen@acme.io",
    role: "Compliance Officer",
    status: "active",
    lastActive: ago(1000 * 60 * 60 * 1),
    mfa: true,
    department: "Compliance",
    initials: "HC",
  },
  {
    id: "u_04",
    name: "Priya Shah",
    email: "priya@acme.io",
    role: "Analyst",
    status: "active",
    lastActive: ago(1000 * 60 * 60 * 3),
    mfa: false,
    department: "Marketing",
    initials: "PS",
  },
  {
    id: "u_05",
    name: "Daniel Owusu",
    email: "daniel@acme.io",
    role: "Viewer",
    status: "active",
    lastActive: ago(1000 * 60 * 60 * 21),
    mfa: true,
    department: "Operations",
    initials: "DO",
  },
  {
    id: "u_06",
    name: "Anna Kowalski",
    email: "anna@acme.io",
    role: "Compliance Officer",
    status: "invited",
    lastActive: ago(1000 * 60 * 60 * 24 * 2),
    mfa: false,
    department: "Legal",
    initials: "AK",
  },
  {
    id: "u_07",
    name: "Tomás Vega",
    email: "tomas@acme.io",
    role: "Analyst",
    status: "suspended",
    lastActive: ago(1000 * 60 * 60 * 24 * 30),
    mfa: false,
    department: "Research",
    initials: "TV",
  },
];

/* ---------- Policies ---------- */

export const policies: Policy[] = [
  {
    id: "pol_001",
    name: "SSN Auto-Encrypt",
    description:
      "Any file containing 1+ Social Security Number must be encrypted with AES-256 and routed to vault storage.",
    trigger: "entity.SSN ≥ 1",
    action: "encrypt(aes256) → route(vault)",
    framework: ["HIPAA", "SOC2"],
    enabled: true,
    hits: 412,
    lastTriggered: ago(1000 * 60 * 17),
    severity: "high",
  },
  {
    id: "pol_002",
    name: "Block Plaintext Secrets",
    description: "Block uploads containing API keys, private keys, or .env credentials.",
    trigger: "entity.API_KEY ≥ 1 OR mime ∈ (.env, .pem)",
    action: "deny + notify(security@acme.io)",
    framework: ["SOC2", "ISO27001"],
    enabled: true,
    hits: 27,
    lastTriggered: ago(1000 * 60 * 9),
    severity: "critical",
  },
  {
    id: "pol_003",
    name: "PHI Tokenization",
    description: "PHI fields must be tokenized before leaving the vault.",
    trigger: "entity.PHI ≥ 1 AND egress",
    action: "tokenize + audit",
    framework: ["HIPAA"],
    enabled: true,
    hits: 88,
    lastTriggered: ago(1000 * 60 * 60 * 4),
    severity: "critical",
  },
  {
    id: "pol_004",
    name: "External Share Watermark",
    description: "All external share links must apply watermark with viewer email + IP.",
    trigger: "share.external = true",
    action: "watermark + 24h expiry",
    framework: ["SOC2"],
    enabled: true,
    hits: 161,
    lastTriggered: ago(1000 * 60 * 31),
    severity: "medium",
  },
  {
    id: "pol_005",
    name: "GDPR Right-to-Erasure",
    description: "Honor erasure requests within 30 days; immutable audit retained.",
    trigger: "request.erasure",
    action: "redact + tombstone",
    framework: ["GDPR", "CCPA"],
    enabled: true,
    hits: 4,
    lastTriggered: ago(1000 * 60 * 60 * 24 * 6),
    severity: "high",
  },
  {
    id: "pol_006",
    name: "Stale File Sweep",
    description: "Internal files untouched 365+ days are archived to cold storage.",
    trigger: "lastAccess > 365d AND sensitivity ≤ internal",
    action: "archive(filecoin)",
    framework: [],
    enabled: false,
    hits: 0,
    severity: "low",
  },
];

/* ---------- API Keys ---------- */

export const apiKeys: ApiKey[] = [
  {
    id: "key_001",
    name: "Production Pipeline",
    prefix: "sk_live_8a4f",
    scopes: ["files:write", "policies:read", "audit:write"],
    createdBy: "Jon Reyes",
    createdAt: ago(1000 * 60 * 60 * 24 * 12),
    lastUsed: ago(1000 * 60 * 3),
    status: "active",
    environment: "production",
  },
  {
    id: "key_002",
    name: "Compliance Audit Reader",
    prefix: "sk_live_b021",
    scopes: ["audit:read", "files:read"],
    createdBy: "Helen Cho",
    createdAt: ago(1000 * 60 * 60 * 24 * 36),
    lastUsed: ago(1000 * 60 * 60 * 4),
    status: "active",
    environment: "production",
  },
  {
    id: "key_003",
    name: "Staging CI",
    prefix: "sk_test_9712",
    scopes: ["files:write", "policies:read"],
    createdBy: "Maya Patel",
    createdAt: ago(1000 * 60 * 60 * 24 * 4),
    lastUsed: ago(1000 * 60 * 60 * 21),
    status: "active",
    environment: "staging",
  },
  {
    id: "key_004",
    name: "Old Webhook (deprecated)",
    prefix: "sk_live_2210",
    scopes: ["webhooks:write"],
    createdBy: "Jon Reyes",
    createdAt: ago(1000 * 60 * 60 * 24 * 220),
    lastUsed: ago(1000 * 60 * 60 * 24 * 60),
    status: "revoked",
    environment: "production",
  },
];

/* ---------- Storage ---------- */

export const storageBackends: StorageBackend[] = [
  {
    id: "sb_vault",
    name: "AEGIS Vault (primary)",
    type: "vault",
    region: "us-east-1",
    capacity: 50_000_000_000_000, // 50 TB
    used: 18_400_000_000_000,
    files: 41_220,
    status: "healthy",
    immutable: false,
    encryption: "client-managed",
    cost: 1240,
  },
  {
    id: "sb_filecoin",
    name: "Filecoin (archival)",
    type: "filecoin",
    capacity: 100_000_000_000_000,
    used: 12_100_000_000_000,
    files: 8_402,
    status: "healthy",
    immutable: true,
    encryption: "client-managed",
    cost: 410,
  },
  {
    id: "sb_arweave",
    name: "Arweave (audit immutable)",
    type: "arweave",
    capacity: 25_000_000_000_000,
    used: 1_220_000_000_000,
    files: 3_120,
    status: "syncing",
    immutable: true,
    encryption: "client-managed",
    cost: 86,
  },
  {
    id: "sb_s3",
    name: "AWS S3 (working set)",
    type: "s3",
    region: "us-west-2",
    capacity: 200_000_000_000_000,
    used: 71_800_000_000_000,
    files: 188_021,
    status: "healthy",
    immutable: false,
    encryption: "kms",
    cost: 3210,
  },
  {
    id: "sb_gcs",
    name: "GCS (DR replica)",
    type: "gcs",
    region: "europe-west4",
    capacity: 200_000_000_000_000,
    used: 60_220_000_000_000,
    files: 162_998,
    status: "degraded",
    immutable: false,
    encryption: "kms",
    cost: 2980,
  },
];

/* ---------- Charts: timeseries / KPIs ---------- */

const seriesRng = makeRng(424242);
export const ingestSeries = Array.from({ length: 30 }, (_, i) => ({
  day: `D${i + 1}`,
  uploads: Math.round(180 + Math.sin(i / 2.4) * 60 + seriesRng() * 80),
  encrypted: Math.round(120 + Math.sin(i / 2.1 + 1) * 50 + seriesRng() * 60),
  blocked: Math.round(8 + Math.cos(i / 1.7) * 5 + seriesRng() * 6),
}));

export const sensitivityDistribution = [
  { name: "Public", value: 1820, key: "public" },
  { name: "Internal", value: 6_412, key: "internal" },
  { name: "Confidential", value: 3_028, key: "confidential" },
  { name: "Restricted", value: 712, key: "restricted" },
];

export const complianceCoverage = [
  { framework: "SOC 2", coverage: 96, controls: 142, gaps: 5 },
  { framework: "HIPAA", coverage: 88, controls: 64, gaps: 8 },
  { framework: "GDPR", coverage: 91, controls: 47, gaps: 4 },
  { framework: "ISO 27001", coverage: 84, controls: 114, gaps: 18 },
  { framework: "PCI-DSS", coverage: 76, controls: 80, gaps: 19 },
  { framework: "FINRA", coverage: 93, controls: 32, gaps: 2 },
];

export const riskHeatmap: { hour: number; day: number; value: number }[] = (() => {
  const rng = makeRng(7174);
  const out: { hour: number; day: number; value: number }[] = [];
  for (let d = 0; d < 7; d++) {
    for (let h = 0; h < 24; h++) {
      const base =
        (Math.sin(h / 3 - 1) + 1) * 0.5 * 0.7 +
        (d === 1 || d === 4 ? 0.2 : 0) +
        (h >= 9 && h <= 17 ? 0.25 : 0);
      const v = Math.min(1, Math.max(0, base + (rng() - 0.5) * 0.25));
      out.push({ hour: h, day: d, value: v });
    }
  }
  return out;
})();

export const threatFeed = [
  {
    id: "t_01",
    title: "Credential leak attempt blocked",
    severity: "critical" as const,
    detail: "1 file with embedded AWS keys quarantined",
    time: ago(1000 * 60 * 9),
  },
  {
    id: "t_02",
    title: "Anomalous bulk download",
    severity: "high" as const,
    detail: "Helen Cho — 412 files in 4m (legal review)",
    time: ago(1000 * 60 * 41),
  },
  {
    id: "t_03",
    title: "MFA disabled on Analyst",
    severity: "medium" as const,
    detail: "User priya@acme.io",
    time: ago(1000 * 60 * 88),
  },
  {
    id: "t_04",
    title: "Unusual geography sign-in",
    severity: "low" as const,
    detail: "Jon Reyes — Singapore (allow-listed)",
    time: ago(1000 * 60 * 60 * 4),
  },
];

export const orgInfo = {
  name: "Atlas Capital",
  plan: "Enterprise",
  usersTotal: 248,
  filesGoverned: 412_881,
  encryptedShare: 0.74,
  policiesActive: 24,
  lastDPIA: ago(1000 * 60 * 60 * 24 * 47),
  region: "us-east-1 / eu-west-1",
};
